uyuchun/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index')
]

uyuchun/mainapp/urls.py
# Imports
from django.urls import path
from . import views
# End Imports


# Config
app_name = 'mainapp'
urlpatterns = [
    path('', views.plug, name='plug'),
    path('testpage123/', views.index, name='index'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:category_slug>/', views.category_detail, name='category_detail'),
    path('shop/<slug:category_slug>/<slug:subcategory_slug>/', views.subcategory_detail, name='subcategory_detail'),
    path(
        'shop/<slug:category_slug>/<slug:subcategory_slug>/<slug:product_slug>/',
        views.product_detail,
        name='product_detail'
    ),
    path('search/', views.search, name='search'),
]
# End Config

uyuchun/uyuchun/urls.py
# Imports
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
# End Imports


# Config
urlpatterns = [
    path('admin/', include('admin.urls', namespace='admin')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('api/', include('api.urls', namespace='api')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# End Config

uyuchun/mainapp/models.py
# Imports
from django.db import models
# End Imports


# Config
class Measure(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    short_name = models.CharField(max_length=200, null=True, blank=True)


class Specification(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    measure = models.ForeignKey(Measure, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='specifications')


class Category(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField()


class SubCategory(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField()
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL,
                                 related_name='subcategories')
    img = models.ImageField(upload_to='subcategories/', null=True, blank=True)


class SubCategorySpecification(models.Model):
    subcategory = models.ForeignKey(SubCategory, null=True, blank=True, on_delete=models.CASCADE,
                                 related_name='subcategoryspecifications')
    specification = models.ForeignKey(Specification, null=True, blank=True, on_delete=models.CASCADE,
                                    related_name='subcategoryspecifications')


class Product(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField()
    subcategory = models.ForeignKey(SubCategory, null=True, blank=True, on_delete=models.SET_NULL,
                                    related_name='products')
    price = models.BigIntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    available = models.BooleanField(default=False)
    published = models.BooleanField(default=False)


class ProductImage(models.Model):
    img = models.ImageField(upload_to='products/', null=True, blank=True)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.SET_NULL, related_name='images')


class ProductSpecification(models.Model):
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE,
                                related_name='productspecifications')
    subcategoryspecification = models.ForeignKey(SubCategorySpecification, null=True, blank=True, on_delete=models.CASCADE,
                                      related_name='productspecifications')
    value = models.CharField(max_length=200, null=True, blank=True)
# End Config

uyuchun/mainapp/forms.py
from django import forms
from .models import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'slug')


class SubCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ('name', 'slug', 'category', 'img')


class SubCategorySpecificationForm(forms.ModelForm):
    class Meta:
        model = SubCategorySpecification
        fields = ('specification', 'subcategory')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'slug', 'subcategory', 'description', 'price', 'available', 'published')


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ('img', 'product')


class MeasureForm(forms.ModelForm):
    class Meta:
        model = Measure
        fields = ('name', 'short_name')


class SpecificationForm(forms.ModelForm):
    class Meta:
        model = Specification
        fields = ('name', 'measure')

uyuchun/mainapp/views.py
# Imports
from django.shortcuts import render, get_object_or_404
from admin.models import Header, IndexPage, Footer
from .models import Category, Product, SubCategory
from django.http import Http404, HttpResponseNotFound
# End Imports


def get_context():
    context = {
        'header': Header.objects.first(),
        'footer': Footer.objects.first(),
        'categories': Category.objects.all(),
    }
    return context


# Config
def plug(request):
    template = 'mainapp/plug.html'
    return render(request, template)


def index(request):
    context = get_context()
    context['indexpage'] = IndexPage.objects.first()
    template = 'mainapp/index.html'
    return render(request, template, context)


def product_list(request):
    context = get_context()
    context['products'] = Product.objects.filter(published=True)
    template = 'mainapp/product_list.html'
    return render(request, template, context)


def category_detail(request, category_slug):
    context = get_context()
    context['category_detail'] = get_object_or_404(Category, slug=category_slug)
    template = 'mainapp/category_detail.html'
    return render(request, template, context)


def subcategory_detail(request, category_slug, subcategory_slug):
    context = get_context()
    context['subcategory_detail'] = get_object_or_404(SubCategory, slug=subcategory_slug)
    template = 'mainapp/subcategory_detail.html'
    return render(request, template, context)


def product_detail(request, category_slug, subcategory_slug, product_slug):
    context = get_context()
    context['product'] = get_object_or_404(Product, slug=product_slug, published=True)
    template = 'mainapp/product_detail.html'
    return render(request, template, context)


def search(request):
    context = get_context()
    if request.GET['category'] == 'all':
        context['products'] = Product.objects.filter(name__icontains=str(request.GET['name']))
    else:
        context['products'] = Product.objects.filter(subcategory__category=int(request.GET['category'])).filter(name__icontains=str(request.GET['name']))
    template = 'mainapp/search.html'
    return render(request, template, context)
# End Config

uyuchun/mainapp/templates/blocks/footer.html
{% load static %}
<footer class="footer">
    <!-- Footer Top -->
    <div class="footer-top section">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer about">
                        <div class="logo">
                            <a href="{% url 'mainapp:index' %}"><img src="{{ footer.logo.url }}" alt="#"></a>
                        </div>
                        <p class="text">{{ footer.description }}</p>
                        <p class="call">Есть вопросы? Звоните нам!<span><a href="{{ footer.phone }}">{{ footer.phone }}</a></span>
                        </p>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <div class="col-lg-2 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer links">
                        <h4>Первый блок ссылок</h4>
                        <ul>
                            <li><a href="#">Ссылка 1</a></li>
                            <li><a href="#">Ссылка 2</a></li>
                            <li><a href="#">Ссылка 3</a></li>
                            <li><a href="#">Ссылка 4</a></li>
                            <li><a href="#">Ссылка 5</a></li>
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <div class="col-lg-2 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer links">
                        <h4>Второй блок ссылок</h4>
                        <ul>
                            <li><a href="#">Ссылка 1</a></li>
                            <li><a href="#">Ссылка 2</a></li>
                            <li><a href="#">Ссылка 3</a></li>
                            <li><a href="#">Ссылка 4</a></li>
                            <li><a href="#">Ссылка 5</a></li>
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <!-- Single Widget -->
                    <div class="single-footer social">
                        <h4>Будьте на связи!</h4>
                        <!-- Single Widget -->
                        <div class="contact">
                            <ul>
                                <li>{{ footer.address }}</li>
                                <li>{{ footer.email }}</li>
                                <li>{{ footer.phone }}</li>
                            </ul>
                        </div>
                        <!-- End Single Widget -->
                        <ul>
                            <li><a href="{{ footer.facebook }}"><i class="ti-facebook"></i></a></li>
                            <li><a href="{{ footer.twitter }}"><i class="ti-twitter"></i></a></li>
                            <li><a href="{{ footer.youtube }}"><i class="ti-youtube"></i></a></li>
                            <li><a href="{{ footer.instagram }}"><i class="ti-instagram"></i></a></li>
                        </ul>
                    </div>
                    <!-- End Single Widget -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer Top -->
    <div class="copyright">
        <div class="container">
            <div class="inner">
                <div class="row">
                    <div class="col-lg-6 col-12">
                        <div class="left">
                            <p>{{ footer.copyright }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

uyuchun/mainapp/templates/blocks/header.html
{% load static %}
<header class="header shop">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-12">
                    <!-- Top Left -->
                    <div class="top-left">
                        <ul class="list-main">
                            <li><i class="ti-headphone-alt"></i> {{ header.phone }}</li>
                            <li><i class="ti-instagram"></i> <a href="https://instagram.com/{{ header.instagram }}">@{{ header.instagram }}</a></li>
                        </ul>
                    </div>
                    <!--/ End Top Left -->
                </div>
                <div class="col-lg-6 col-md-12 col-12">
                    <!-- Top Right -->
                    <div class="right-content">
                        <ul class="list-main">
                            <li><i class="ti-location-pin"></i> {{ header.address }}</li>
                            <li><i class="ti-alarm-clock"></i> {{ header.worktime }}</li>
{#                            <li><i class="ti-user"></i> <a href="#">My account</a></li>#}
{#                            <li><i class="ti-power-off"></i><a href="login.html#">Login</a></li>#}
                        </ul>
                    </div>
                    <!-- End Top Right -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <div class="middle-inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-12">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="index.html"><img src="{{ header.logo.url }}" alt="logo"></a>
                    </div>
                    <!--/ End Logo -->
                    <!-- Search Form -->
                    <div class="search-top">
                        <div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
                        <!-- Search Form -->
                        <div class="search-top">
                            <form class="search-form">
                                <input type="text" placeholder="Search here..." name="search">
                                <button value="search" type="submit"><i class="ti-search"></i></button>
                            </form>
                        </div>
                        <!--/ End Search Form -->
                    </div>
                    <!--/ End Search Form -->
                    <div class="mobile-nav"></div>
                </div>
                <div class="col-lg-8 col-md-7 col-12">
                    <div class="search-bar-top">
                        <div class="search-bar">
                            <form action="{% url 'mainapp:search' %}" method="GET" style="width: auto;">
                            <select name="category">
                                <option selected="selected" value="all">Все категории</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                                <input name="name" placeholder="Поиск....." type="search">
                                <button type="submit" class="btnn"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-12">
                    <div class="right-bar">
                        <!-- Search Form -->
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="sinlge-bar shopping">
                            <a href="#" class="single-icon"><i class="ti-bag"></i> <span
                                    class="total-count">2</span></a>
                            <!-- Shopping Item -->
                            {% comment %}
                            <div class="shopping-item">
                                <div class="dropdown-cart-header">
                                    <span>2 Items</span>
                                    <a href="#">View Cart</a>
                                </div>
                                <ul class="shopping-list">
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{% static 'images/product-1.jpg' %}" alt="#"></a>
                                        <h4><a href="#">Woman Ring</a></h4>
                                        <p class="quantity">1x - <span class="amount">$99.00</span></p>
                                    </li>
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{% static 'images/product-2.jpg' %}" alt="#"></a>
                                        <h4><a href="#">Woman Necklace</a></h4>
                                        <p class="quantity">1x - <span class="amount">$35.00</span></p>
                                    </li>
                                </ul>
                                <div class="bottom">
                                    <div class="total">
                                        <span>Total</span>
                                        <span class="total-amount">$134.00</span>
                                    </div>
                                    <a href="checkout.html" class="btn animate">Checkout</a>
                                </div>
                            </div>
                            {% endcomment %}
                            <!--/ End Shopping Item -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="cat-nav-head">
                <div class="row">
                    <div class="col-12">
                        <div class="menu-area">
                            <!-- Main Menu -->
                            <nav class="navbar navbar-expand-lg">
                                <div class="navbar-collapse">
                                    <div class="nav-inner">
                                        <ul class="nav main-menu menu navbar-nav">
                                            <li class=""><a href="{% url 'mainapp:index' %}">Главная</a></li>
                                            {% if '/shop/' in request.path %}
                                                <li class="active"><a href="{% url 'mainapp:product_list' %}">Магазин</a></li>
                                            {% else %}
                                                <li class=""><a href="{% url 'mainapp:product_list' %}">Магазин</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                            <!--/ End Main Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Inner -->
</header>

uyuchun/mainapp/templates/blocks/main_header.html
{% load static %}
<header class="header shop">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-12">
                    <!-- Top Left -->
                    <div class="top-left">
                        <ul class="list-main">
                            <li><i class="ti-headphone-alt"></i> {{ header.phone }}</li>
                            <li><i class="ti-instagram"></i> <a href="https://instagram.com/{{ header.instagram }}">@{{ header.instagram }}</a></li>
                        </ul>
                    </div>
                    <!--/ End Top Left -->
                </div>
                <div class="col-lg-6 col-md-12 col-12">
                    <!-- Top Right -->
                    <div class="right-content">
                        <ul class="list-main">
                            <li><i class="ti-location-pin"></i> {{ header.address }}</li>
                            <li><i class="ti-alarm-clock"></i> {{ header.worktime }}</li>
{#                            <li><i class="ti-user"></i> <a href="#">My account</a></li>#}
{#                            <li><i class="ti-power-off"></i><a href="login.html#">Login</a></li>#}
                        </ul>
                    </div>
                    <!-- End Top Right -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <div class="middle-inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-12">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="index.html"><img src="{{ header.logo.url }}" alt="logo"></a>
                    </div>
                    <!--/ End Logo -->
                    <!-- Search Form -->
                    <div class="search-top">
                        <div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
                        <!-- Search Form -->
                        <div class="search-top">
                            <form class="search-form">
                                <input type="text" placeholder="Search here..." name="search">
                                <button value="search" type="submit"><i class="ti-search"></i></button>
                            </form>
                        </div>
                        <!--/ End Search Form -->
                    </div>
                    <!--/ End Search Form -->
                    <div class="mobile-nav"></div>
                </div>
                <div class="col-lg-8 col-md-7 col-12">
                    <div class="search-bar-top">
                        <div class="search-bar">
                            <form action="{% url 'mainapp:search' %}" method="GET" style="width: auto;">
                            <select name="category">
                                <option selected="selected" value="all">Все категории</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                                <input name="name" placeholder="Поиск....." type="search">
                                <button type="submit" class="btnn"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-12">
                    <div class="right-bar">
                        <!-- Search Form -->
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="sinlge-bar">
                            <a href="#" class="single-icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                        </div>
                        <div class="sinlge-bar shopping">
                            <a href="#" class="single-icon"><i class="ti-bag"></i> <span
                                    class="total-count">2</span></a>
                            <!-- Shopping Item -->
                            {% comment %}
                            <div class="shopping-item">
                                <div class="dropdown-cart-header">
                                    <span>2 Items</span>
                                    <a href="#">View Cart</a>
                                </div>
                                <ul class="shopping-list">
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{% static 'images/product-1.jpg' %}" alt="#"></a>
                                        <h4><a href="#">Woman Ring</a></h4>
                                        <p class="quantity">1x - <span class="amount">$99.00</span></p>
                                    </li>
                                    <li>
                                        <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                        <a class="cart-img" href="#"><img src="{% static 'images/product-2.jpg' %}" alt="#"></a>
                                        <h4><a href="#">Woman Necklace</a></h4>
                                        <p class="quantity">1x - <span class="amount">$35.00</span></p>
                                    </li>
                                </ul>
                                <div class="bottom">
                                    <div class="total">
                                        <span>Total</span>
                                        <span class="total-amount">$134.00</span>
                                    </div>
                                    <a href="checkout.html" class="btn animate">Checkout</a>
                                </div>
                            </div>
                            {% endcomment %}
                            <!--/ End Shopping Item -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="cat-nav-head">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="all-category">
                            <h3 class="cat-heading"><i class="fa fa-bars" aria-hidden="true"></i>Категории</h3>
                            <ul class="main-category">
                                  {% for category in categories %}
                                      <li><a data-submenu="#sub_menu{{ category.id }}" href="{% url 'mainapp:category_detail' category.slug %}">{{ category.name }}<i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                        <ul class="sub-category" id="sub_menu{{ category.id }}">
                                            {% for subcategory in category.subcategories.all %}
                                                <li><a href="{% url 'mainapp:subcategory_detail' category.slug subcategory.slug %}">{{ subcategory.name }}</a></li>
                                            {% endfor %}
										</ul>
                                      </li>
                                  {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-9 col-12">
                        <div class="menu-area">
                            <!-- Main Menu -->
                            <nav class="navbar navbar-expand-lg">
                                <div class="navbar-collapse">
                                    <div class="nav-inner">
                                        <ul class="nav main-menu menu navbar-nav">
                                                <li class="active"><a href="{% url 'mainapp:index' %}">Главная</a></li>
                                                <li class=""><a href="{% url 'mainapp:product_list' %}">Магазин</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                            <!--/ End Main Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Inner -->
</header>